using DreamersCode.Utilities.Lookups.Currencies.Models;
#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif
using System.Collections.Generic;

namespace DreamersCode.Utilities.Lookups.Currencies
{
    /// <summary>
    /// Contains a list of all the currencies against which queries can be made
    /// </summary>
    public static class CurrencyCollection
    {
#if NET8_0_OR_GREATER
        /// <summary>
        /// Represents the set of currencies as per ISO-4217
        /// </summary>
        public static FrozenSet<Currency> AllCurrencies { get; internal set; }
#else
        /// <summary>
        /// Represents the set of currencies as per ISO-4217
        /// </summary>
        public static IReadOnlyCollection<Currency> AllCurrencies{ get; internal set; }
#endif

        /// <summary>
        /// Constructor
        /// </summary>
        static CurrencyCollection()
        {
            AllCurrencies = new List<Currency>()
            {
                new Currency(alphabeticCode:"AFN", numericCode:971, currencySymbol:"؋", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Afghan afghani") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Pul") }),
                new Currency(alphabeticCode:"ALL", numericCode:008, currencySymbol:"Lek", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Albanian lek") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Qintar") }),
                new Currency(alphabeticCode:"DZD", numericCode:012, currencySymbol:"DA", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Algerian dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"AOA", numericCode:973, currencySymbol:"Kz", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Angolan kwanza") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cêntimo") }),
                new Currency(alphabeticCode:"ARS", numericCode:032, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Argentine peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"AMD", numericCode:051, currencySymbol:"֏", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Armenian dram") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Luma") }),
                new Currency(alphabeticCode:"AWG", numericCode:533, currencySymbol:"ƒ", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Aruban florin") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"AUD", numericCode:036, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Australian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"AZN", numericCode:944, currencySymbol:"₼", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Azerbaijani manat") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Qəpik") }),
                new Currency(alphabeticCode:"BSD", numericCode:044, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bahamian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"BHD", numericCode:048, currencySymbol:"BD", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bahraini dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fils") }),
                new Currency(alphabeticCode:"BDT", numericCode:050, currencySymbol:"৳", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bangladeshi taka") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Poisha") }),
                new Currency(alphabeticCode:"BBD", numericCode:052, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Barbadian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"BYN", numericCode:933, currencySymbol:"Br", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Belarusian ruble") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Copeck") }),
                new Currency(alphabeticCode:"BZD", numericCode:084, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Belize dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"BMD", numericCode:060, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bermudian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"BTN", numericCode:064, currencySymbol:"Nu", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bhutanese ngultrum") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Chetrum") }),
                new Currency(alphabeticCode:"BOB", numericCode:068, currencySymbol:"Bs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bolivian boliviano") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"BAM", numericCode:977, currencySymbol:"KM", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bosnia and Herzegovina convertible mark") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fening") }),
                new Currency(alphabeticCode:"BWP", numericCode:072, currencySymbol:"P", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Botswana pula") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Thebe") }),
                new Currency(alphabeticCode:"BRL", numericCode:986, currencySymbol:"R$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Brazilian real") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"BND", numericCode:096, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Brunei dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sen") }),
                new Currency(alphabeticCode:"BGN", numericCode:975, currencySymbol:"Lev", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Bulgarian lev") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Stotinka") }),
                new Currency(alphabeticCode:"MMK", numericCode:104, currencySymbol:"Ks", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Burmese kyat") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Pya") }),
                new Currency(alphabeticCode:"BIF", numericCode:108, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Burundian franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"KHR", numericCode:116, currencySymbol:"៛", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cambodian riel") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sen") }),
                new Currency(alphabeticCode:"CAD", numericCode:124, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Canadian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"CVE", numericCode:132, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cape Verdean escudo") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"KYD", numericCode:136, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cayman Islands dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"XAF", numericCode:950, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Central African CFA franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"XPF", numericCode:953, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"CFP franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"CLP", numericCode:152, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Chilean peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"COP", numericCode:170, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Colombian peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"KMF", numericCode:174, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Comorian franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"CDF", numericCode:976, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Congolese franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"CRC", numericCode:188, currencySymbol:"₡", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Costa Rican colón") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Céntimo") }),
                new Currency(alphabeticCode:"CUP", numericCode:192, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cuban peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"CZK", numericCode:203, currencySymbol:"Kč", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Czech koruna") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Heller") }),
                new Currency(alphabeticCode:"DKK", numericCode:208, currencySymbol:"kr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Danish krone") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Øre") }),
                new Currency(alphabeticCode:"DJF", numericCode:262, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Djiboutian franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"DOP", numericCode:214, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Dominican peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"XCD", numericCode:951, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Eastern Caribbean dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"EGP", numericCode:818, currencySymbol:"LE", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Egyptian pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piastre[B]") }),
                new Currency(alphabeticCode:"ERN", numericCode:232, currencySymbol:"Nkf", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Eritrean nakfa") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"ETB", numericCode:230, currencySymbol:"Br", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ethiopian birr") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Santim") }),
                new Currency(alphabeticCode:"EUR", numericCode:978, currencySymbol:"€", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Euro") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"FKP", numericCode:238, currencySymbol:"£", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Falkland Islands pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Penny") }),
                new Currency(alphabeticCode:"FJD", numericCode:242, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fijian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"GMD", numericCode:270, currencySymbol:"D", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Gambian dalasi") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Butut") }),
                new Currency(alphabeticCode:"GEL", numericCode:981, currencySymbol:"₾", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Georgian lari") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tetri") }),
                new Currency(alphabeticCode:"GHS", numericCode:936, currencySymbol:"₵", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ghanaian cedi") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Pesewa") }),
                new Currency(alphabeticCode:"GIP", numericCode:292, currencySymbol:"£", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Gibraltar pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Penny") }),
                new Currency(alphabeticCode:"GTQ", numericCode:320, currencySymbol:"Q", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Guatemalan quetzal") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"GNF", numericCode:324, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Guinean franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"GYD", numericCode:328, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Guyanese dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"HTG", numericCode:332, currencySymbol:"G", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Haitian gourde") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"HNL", numericCode:340, currencySymbol:"L", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Honduran lempira") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"HKD", numericCode:344, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Hong Kong dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"HUF", numericCode:348, currencySymbol:"Ft", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Hungarian forint") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fillér") }),
                new Currency(alphabeticCode:"ISK", numericCode:352, currencySymbol:"kr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Icelandic króna") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Eyrir") }),
                new Currency(alphabeticCode:"INR", numericCode:356, currencySymbol:"₹", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Indian rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Paisa") }),
                new Currency(alphabeticCode:"IDR", numericCode:360, currencySymbol:"Rp", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Indonesian rupiah") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sen") }),
                new Currency(alphabeticCode:"IRR", numericCode:364, currencySymbol:"Rls", minorUnit:1, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Iranian rial") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Rial") }),
                new Currency(alphabeticCode:"IQD", numericCode:368, currencySymbol:"ID", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Iraqi dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fils") }),
                new Currency(alphabeticCode:"ILS", numericCode:376, currencySymbol:"₪", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Israeli new shekel") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Agora") }),
                new Currency(alphabeticCode:"JMD", numericCode:388, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Jamaican dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"JPY", numericCode:392, currencySymbol:"¥", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Japanese yen") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sen[C]") }),
                new Currency(alphabeticCode:"JOD", numericCode:400, currencySymbol:"JD", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Jordanian dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piastre[H]") }),
                new Currency(alphabeticCode:"KZT", numericCode:398, currencySymbol:"₸", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kazakhstani tenge") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tıyn") }),
                new Currency(alphabeticCode:"KES", numericCode:404, currencySymbol:"Sh", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kenyan shilling") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"KWD", numericCode:414, currencySymbol:"KD", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kuwaiti dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fils") }),
                new Currency(alphabeticCode:"KGS", numericCode:417, currencySymbol:"som", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kyrgyz som") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tyiyn") }),
                new Currency(alphabeticCode:"LAK", numericCode:418, currencySymbol:"₭", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Lao kip") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Att") }),
                new Currency(alphabeticCode:"LBP", numericCode:422, currencySymbol:"LL", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Lebanese pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piastre") }),
                new Currency(alphabeticCode:"LSL", numericCode:426, currencySymbol:"M", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Lesotho loti") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sente") }),
                new Currency(alphabeticCode:"LRD", numericCode:430, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Liberian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"LYD", numericCode:434, currencySymbol:"LD", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Libyan dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Dirham") }),
                new Currency(alphabeticCode:"MOP", numericCode:446, currencySymbol:"MOP$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Macanese pataca") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Avo") }),
                new Currency(alphabeticCode:"MKD", numericCode:807, currencySymbol:"DEN", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Macedonian denar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Deni") }),
                new Currency(alphabeticCode:"MGA", numericCode:969, currencySymbol:"Ar", minorUnit:5, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Malagasy ariary") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Iraimbilanja") }),
                new Currency(alphabeticCode:"MWK", numericCode:454, currencySymbol:"K", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Malawian kwacha") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tambala") }),
                new Currency(alphabeticCode:"MYR", numericCode:458, currencySymbol:"RM", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Malaysian ringgit") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sen") }),
                new Currency(alphabeticCode:"MVR", numericCode:462, currencySymbol:"Rf", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Maldivian rufiyaa") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Laari") }),
                new Currency(alphabeticCode:"MRU", numericCode:929, currencySymbol:"UM", minorUnit:5, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Mauritanian ouguiya") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Khoums") }),
                new Currency(alphabeticCode:"MUR", numericCode:480, currencySymbol:"Rs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Mauritian rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"MXN", numericCode:484, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Mexican peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"MDL", numericCode:498, currencySymbol:"Lei", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Moldovan leu") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ban") }),
                new Currency(alphabeticCode:"MNT", numericCode:496, currencySymbol:"₮", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Mongolian tögrög") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Möngö") }),
                new Currency(alphabeticCode:"MAD", numericCode:504, currencySymbol:"DH", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Moroccan dirham") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"MZN", numericCode:943, currencySymbol:"Mt", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Mozambican metical") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"NAD", numericCode:516, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Namibian dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"NPR", numericCode:524, currencySymbol:"Rs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Nepalese rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Paisa") }),
                new Currency(alphabeticCode:"ANG", numericCode:532, currencySymbol:"ƒ", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Netherlands Antillean guilder") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"TWD", numericCode:901, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"New Taiwan dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"NZD", numericCode:554, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"New Zealand dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"NIO", numericCode:558, currencySymbol:"C$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Nicaraguan córdoba") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centavo") }),
                new Currency(alphabeticCode:"NGN", numericCode:566, currencySymbol:"₦", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Nigerian naira") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kobo") }),
                new Currency(alphabeticCode:"KPW", numericCode:408, currencySymbol:"₩", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"North Korean won") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Chon") }),
                new Currency(alphabeticCode:"NOK", numericCode:578, currencySymbol:"kr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Norwegian krone") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Øre") }),
                new Currency(alphabeticCode:"OMR", numericCode:512, currencySymbol:"RO", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Omani rial") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Baisa") }),
                new Currency(alphabeticCode:"PKR", numericCode:586, currencySymbol:"Rs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Pakistani rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Paisa") }),
                new Currency(alphabeticCode:"PAB", numericCode:590, currencySymbol:"B/", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Panamanian balboa") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centésimo") }),
                new Currency(alphabeticCode:"PGK", numericCode:598, currencySymbol:"K", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Papua New Guinean kina") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Toea") }),
                new Currency(alphabeticCode:"PYG", numericCode:600, currencySymbol:"₲", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Paraguayan guaraní") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Céntimo") }),
                new Currency(alphabeticCode:"PEN", numericCode:604, currencySymbol:"S/", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Peruvian sol") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Céntimo") }),
                new Currency(alphabeticCode:"PHP", numericCode:608, currencySymbol:"₱", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Philippine peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sentimo") }),
                new Currency(alphabeticCode:"PLN", numericCode:985, currencySymbol:"zł", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Polish złoty") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Grosz") }),
                new Currency(alphabeticCode:"QAR", numericCode:634, currencySymbol:"QR", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Qatari riyal") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Dirham") }),
                new Currency(alphabeticCode:"CNY", numericCode:156, currencySymbol:"¥", minorUnit:10, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Renminbi") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Jiao[G]") }),
                new Currency(alphabeticCode:"RON", numericCode:946, currencySymbol:"Lei", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Romanian leu") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ban") }),
                new Currency(alphabeticCode:"RUB", numericCode:643, currencySymbol:"₽", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Russian ruble") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kopeck") }),
                new Currency(alphabeticCode:"RWF", numericCode:646, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Rwandan franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"SHP", numericCode:654, currencySymbol:"£", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Saint Helena pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Penny") }),
                new Currency(alphabeticCode:"WST", numericCode:882, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Samoan tālā") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sene") }),
                new Currency(alphabeticCode:"STN", numericCode:930, currencySymbol:"Db", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"São Tomé and Príncipe dobra") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cêntimo") }),
                new Currency(alphabeticCode:"SAR", numericCode:682, currencySymbol:"Rls", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Saudi riyal") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Halala") }),
                new Currency(alphabeticCode:"RSD", numericCode:941, currencySymbol:"DIN", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Serbian dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Para") }),
                new Currency(alphabeticCode:"SCR", numericCode:690, currencySymbol:"Rs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Seychellois rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SLE", numericCode:925, currencySymbol:"Le", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sierra Leonean leone") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SGD", numericCode:702, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Singapore dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SBD", numericCode:090, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Solomon Islands dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SOS", numericCode:706, currencySymbol:"Shs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Somali shilling") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"ZAR", numericCode:710, currencySymbol:"R", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"South African rand") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"KRW", numericCode:410, currencySymbol:"₩", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"South Korean won") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Jeon") }),
                new Currency(alphabeticCode:"SSP", numericCode:728, currencySymbol:"", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"South Sudanese pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piaster") }),
                new Currency(alphabeticCode:"LKR", numericCode:144, currencySymbol:"Rs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sri Lankan rupee") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"GBP", numericCode:826, currencySymbol:"£", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sterling") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Penny") }),
                new Currency(alphabeticCode:"SDG", numericCode:938, currencySymbol:"LS", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Sudanese pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piastre") }),
                new Currency(alphabeticCode:"SRD", numericCode:968, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Surinamese dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SZL", numericCode:748, currencySymbol:"E", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Swazi lilangeni") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"SEK", numericCode:752, currencySymbol:"kr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Swedish krona") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Öre") }),
                new Currency(alphabeticCode:"CHF", numericCode:756, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Swiss franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Rappen") }),
                new Currency(alphabeticCode:"CHF", numericCode:756, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Swiss franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Rappen[J]") }),
                new Currency(alphabeticCode:"SYP", numericCode:760, currencySymbol:"LS", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Syrian pound") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Piastre") }),
                new Currency(alphabeticCode:"TJS", numericCode:972, currencySymbol:"SM", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tajikistani somoni") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Diram") }),
                new Currency(alphabeticCode:"TZS", numericCode:834, currencySymbol:"Shs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tanzanian shilling") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"THB", numericCode:764, currencySymbol:"฿", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Thai baht") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Satang") }),
                new Currency(alphabeticCode:"TOP", numericCode:776, currencySymbol:"T$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tongan paʻanga[K]") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Seniti") }),
                new Currency(alphabeticCode:"TTD", numericCode:780, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Trinidad and Tobago dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"TND", numericCode:788, currencySymbol:"د.ت", minorUnit:1000, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tunisian dinar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Millime") }),
                new Currency(alphabeticCode:"TRY", numericCode:949, currencySymbol:"₺", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Turkish lira") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kuruş") }),
                new Currency(alphabeticCode:"TMT", numericCode:934, currencySymbol:"m", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Turkmenistani manat") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tenge") }),
                new Currency(alphabeticCode:"UGX", numericCode:800, currencySymbol:"Shs", minorUnit:0, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ugandan shilling") }, fractionalUnitNames: new List<DisplayInfo>(0)),
                new Currency(alphabeticCode:"UAH", numericCode:980, currencySymbol:"₴", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ukrainian hryvnia") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Kopeck") }),
                new Currency(alphabeticCode:"AED", numericCode:784, currencySymbol:"Dhs", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"United Arab Emirates dirham") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fils") }),
                new Currency(alphabeticCode:"USD", numericCode:840, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"United States dollar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"UYU", numericCode:858, currencySymbol:"$", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Uruguayan peso") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centésimo") }),
                new Currency(alphabeticCode:"UZS", numericCode:860, currencySymbol:"soum", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Uzbekistani sum") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Tiyin") }),
                new Currency(alphabeticCode:"VUV", numericCode:548, currencySymbol:"VT", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Vanuatu vatu") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Cent") }),
                new Currency(alphabeticCode:"VED", numericCode:926, currencySymbol:"Bs.D", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Venezuelan digital bolívar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Céntimo") }),
                new Currency(alphabeticCode:"VES", numericCode:928, currencySymbol:"Bs.S", minorUnit:1, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Venezuelan sovereign bolívar") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Céntimo") }),
                new Currency(alphabeticCode:"VND", numericCode:704, currencySymbol:"₫", minorUnit:10, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Vietnamese đồng") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Hào[L]") }),
                new Currency(alphabeticCode:"XOF", numericCode:952, currencySymbol:"Fr", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"West African CFA franc") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Centime") }),
                new Currency(alphabeticCode:"YER", numericCode:886, currencySymbol:"Rls", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Yemeni rial") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Fils") }),
                new Currency(alphabeticCode:"ZMW", numericCode:967, currencySymbol:"K", minorUnit:100, currencyNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Zambian kwacha") }, fractionalUnitNames: new List<DisplayInfo>(){new DisplayInfo(langCode:"eng", displayValue:"Ngwee") })
            }
#if NET8_0_OR_GREATER
                  .ToFrozenSet()
#endif
            ;

        }

    }
}
